import type { ChatMessage } from "@/services/chatService";

const SYSTEM_PROMPT = `You are David, an expert AI Career Advisor & Government Job Specialist for DeshKiSeva (India's premier career & exam portal).
You help candidates with:
- Finding Government & Private Jobs (SSC, Banking, Railways, UPSC, Defence, Tech, Management).
- Preparing for 20+ Govt Exams with 1,000+ Mock Tests (SSC CGL/CHSL/MTS/CPO, IBPS PO/Clerk, SBI PO/Clerk, RRB NTPC/Group D/ALP/JE, AFCAT, CDS, NDA, BPSC, UPPSC, CTET).
- Building ATS-friendly resumes with 1-to-1 PDF export.
- Tracking Admit Cards & Exam Results.

Be encouraging, professional, concise, and provide clear markdown formatted answers with bullet points.`;

export async function callRealtimeOpenAIChatGPT(
  messages: ChatMessage[],
  apiKeyOverride?: string
): Promise<string> {
  const apiKey =
    apiKeyOverride?.trim() ||
    localStorage.getItem("openai_api_key") ||
    import.meta.env.VITE_OPENAI_API_KEY ||
    "";

  if (!apiKey) {
    throw new Error("NO_API_KEY");
  }

  const apiMessages = [
    { role: "system", content: SYSTEM_PROMPT },
    ...messages.map((m) => ({ role: m.role, content: m.content })),
  ];

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey.trim()}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      messages: apiMessages,
      temperature: 0.7,
      max_tokens: 800,
    }),
  });

  if (!response.ok) {
    const errorJson = await response.json().catch(() => ({}));
    const errMsg = errorJson?.error?.message || `OpenAI API returned error ${response.status}`;
    throw new Error(errMsg);
  }

  const data = await response.json();
  const reply = data.choices?.[0]?.message?.content;

  if (!reply) {
    throw new Error("No response generated by ChatGPT.");
  }

  return reply;
}
